### ISSUE TITLE
项目无法启动

### ISSUE THREAD

**Issue by wiiler** [qiuxiang/react-native-baidumap-sdk#164]
react-native link react-native-baidumap-sdk 后 ，编译失败
react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew in
stallDebug)...

> Configure project :app
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignore
d, as it is below the minimum supported version (28.0.3) for Android Grad
le Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your b
uild.gradle file, as each version of the Android Gradle Plugin now has a 
default version of the build tools.

> Configure project :react-native-baidumap-sdk
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

**Comment by qiuxiang** [comment]
这里都没有提到出错的原因

**Comment by wiiler** [comment]
react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew in
stallDebug)...

> Configure project :app
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignore
d, as it is below the minimum supported version (28.0.3) for Android Grad
le Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your b
uild.gradle file, as each version of the Android Gradle Plugin now has a 
default version of the build tools.

> Configure project :react-native-baidumap-sdk
WARNING: Configuration 'compile' is obsolete and has been replaced with '
implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'react-native-baidumap-sdk' is using version 1.2.41.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Could not install the app on the device, read the error above for details
.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at runOnAllDevices (/Users/weiquan02/Documents/icode/juping/mapsdk/jupingbanjing/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/weiquan02/Documents/icode/juping/mapsdk/jupingbanjing/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/weiquan02/Documents/icode/juping/mapsdk/jupingbanjing/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by wiiler** [comment]
> 这里都没有提到出错的原因

react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew in
stallDebug)...

> Configure project :app
WARNING: The specified Android SDK Build Tools version (28.0.2) is ignore
d, as it is below the minimum supported version (28.0.3) for Android Grad
le Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.2'" from your b
uild.gradle file, as each version of the Android Gradle Plugin now has a 
default version of the build tools.

> Configure project :react-native-baidumap-sdk
WARNING: Configuration 'compile' is obsolete and has been replaced with '
implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'react-native-baidumap-sdk' is using version 1.2.41.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Could not install the app on the device, read the error above for details
.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:602:13)
    at Object.execFileSync (child_process.js:622:13)
    at runOnAllDevices (/Users/weiquan02/Documents/icode/juping/mapsdk/jupingbanjing/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/Users/weiquan02/Documents/icode/juping/mapsdk/jupingbanjing/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/Users/weiquan02/Documents/icode/juping/mapsdk/jupingbanjing/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by qiuxiang** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'react-native-baidumap-sdk' is using version 1.2.41.

错误的原因是这个，kotlin Plugin 过低。

试下 `react-native-baidumap-sdk@next` 这个版本。

**Comment by wiiler** [comment]
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'react-native-baidumap-sdk' is using version 1.2.41.
> 
> 错误的原因是这个，kotlin Plugin 过低。
> 
> 试下 `react-native-baidumap-sdk@next` 这个版本。

 不报错了，但是android 模拟器一闪而过，再次打开也是一闪而过

**Comment by qiuxiang** [comment]
看 logcat，应该是没初始化

**Comment by wiiler** [comment]
> 看 logcat，应该是没初始化

react native 怎么看logcat

**Comment by qiuxiang** [comment]
最好用 Android Studio

**Comment by wiiler** [comment]
> 最好用 Android Studio

PID: 4167
    java.lang.ExceptionInInitializerError
        at com.baidu.platform.comapi.map.i.a(Unknown Source:0)
        at com.baidu.mapapi.map.MapView.a(Unknown Source:2)
        at com.baidu.mapapi.map.MapView.<init>(Unknown Source:17)
        at cn.qiuxiang.react.baidumap.mapview.BaiduMapView.<init>(BaiduMapView.kt:24)
        at cn.qiuxiang.react.baidumap.mapview.BaiduMapViewManager.createViewInstance(BaiduMapViewManager.kt:26)
        at cn.qiuxiang.react.baidumap.mapview.BaiduMapViewManager.createViewInstance(BaiduMapViewManager.kt:20)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:42)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:260)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1056)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: you have not supplyed the global app context info from SDKInitializer.initialize(Context) function.
        at com.baidu.platform.comapi.a.e(Unknown Source:8)
        at com.baidu.mapapi.BMapManager.getContext(Unknown Source:4)
        at com.baidu.platform.comapi.map.i.<clinit>(Unknown Source:0)
        at com.baidu.platform.comapi.map.i.a(Unknown Source:0) 
        at com.baidu.mapapi.map.MapView.a(Unknown Source:2) 
        at com.baidu.mapapi.map.MapView.<init>(Unknown Source:17) 
        at cn.qiuxiang.react.baidumap.mapview.BaiduMapView.<init>(BaiduMapView.kt:24) 
        at cn.qiuxiang.react.baidumap.mapview.BaiduMapViewManager.createViewInstance(BaiduMapViewManager.kt:26) 
        at cn.qiuxiang.react.baidumap.mapview.BaiduMapViewManager.createViewInstance(BaiduMapViewManager.kt:20) 
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:42) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:260) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1085) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1056) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:761) 
        at android.view.Choreographer.doFrame(Choreographer.java:693) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6680) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-02-18 18:49:37.529 2302-3489/system_process E/EGL_emulation: tid 3489: eglSurfaceAttrib(1354): error 0x3009 (EGL_BAD_MATCH)
2019-02-18 18:49:37.998 2986-3097/com.android.launcher3 E/EGL_emulation: tid 3097: eglSurfaceAttrib(1354): error 0x3009 (EGL_BAD_MATCH)


大佬，看看，报的错误

**Comment by qiuxiang** [comment]
你没初始化把

**Comment by wiiler** [comment]
> 你没初始化吧

 确实好了，但是没有数据，这是怎么回事
<img width="356" alt="1" src="https://user-images.githubusercontent.com/9715482/52951088-ce075a00-33bb-11e9-9e97-1c5536449821.png">

**Comment by GreatAuk** [comment]
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'react-native-baidumap-sdk' is using version 1.2.41.
> 
> 错误的原因是这个，kotlin Plugin 过低。
> 
> 试下 `react-native-baidumap-sdk@next` 这个版本。

为什么npm安装的还是0.6.0的版本，如果不加@next
