### ISSUE TITLE
运行安卓example.apk,然后打开另一个app, example.apk闪退了

### ISSUE THREAD

**Issue by hm496** [qiuxiang/react-native-baidumap-sdk#177]
安卓7.1.1
小米6

java.lang.RuntimeException: Error receiving broadcast Intent { act=permission check ok flg=0x10 } in cn.qiuxiang.react.baidumap.modules.BaiduMapInitializerModule$SDKReceiver@dffceae
  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1138)
  at android.os.Handler.handleCallback(Handler.java:754)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:163)
  at android.app.ActivityThread.main(ActivityThread.java:6381)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
Caused by: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
  at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
  at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:32)
  at cn.qiuxiang.react.baidumap.modules.BaiduMapInitializerModule$SDKReceiver.onReceive(BaiduMapInitializerModule.kt:19)
  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1128)
  ... 7 more

**Comment by zhllucky** [comment]
@qiuxiang  这个bug有预期什么时候解决吗。现在碰到了同样的问题。

**Comment by zhllucky** [comment]
@hm496   请问你那边解决了这个问题吗。
