### ISSUE TITLE
断网闪退问题

### ISSUE THREAD

**Issue by caoruonan** [qiuxiang/react-native-baidumap-sdk#189]
您好，我想问一下，安卓和ios安装后好用，但是一但断网几天或者手动修改系统时间之后app就会闪退打不开的情况，麻烦你问一下是什么问题？安卓联网后修改为正常时间后恢复正常，ios则彻底打不开，麻烦问一下怎么解决？
android断网修改时间后报错

`2022-04-26 11:42:26.588 22358-22405/? E/PermissionCheck: permission check result is: -11
2022-04-26 11:42:26.663 22358-22358/? E/baidumapsdk: Authentication Error
    =============================================
    ----------------- 鉴权错误信息 ------------
    sha1;package:1A:xxxx
    key:xxxx
    errorcode: -11 uid: -1 appid -1 msg: httpsPost failed,IOException:Chain validation failed
    请仔细核查 SHA1、package与key申请信息是否对应，key是否删除，平台是否匹配
    errorcode为230时，请参考论坛链接：
    http://bbs.lbsyun.baidu.com/forum.php?mod=viewthread&tid=106461
    =============================================
2022-04-26 11:42:26.770 22358-22404/? E/ReactNativeJS: { [Error: permission check error] framesToPop: 1, code: '-11' }
    
    --------- beginning of crash
2022-04-26 11:42:26.773 22358-22405/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.pjjh, PID: 22358
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:207)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:784)
2022-04-26 11:42:26.778 865-3135/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.`

**Comment by qiuxiang** [comment]
看起来是 key 不对

**Comment by qiuxiang** [comment]
不过具体错误也还看不出来，我先试试能不能重现
