### ISSUE TITLE
应用启动崩溃

### ISSUE THREAD

**Issue by Jeijie** [qiuxiang/react-native-baidumap-sdk#258]
应用集成了插件"react-native-baidumap-sdk": "^0.6.1-2",，启动崩溃，下面是日志
12-16 17:06:22.330 D/AndroidRuntime(22586): Shutting down VM
--------- beginning of crash
12-16 17:06:22.330 E/AndroidRuntime(22586): FATAL EXCEPTION: main
12-16 17:06:22.330 E/AndroidRuntime(22586): Process: com.grgbanking.nuwa, PID: 22586
12-16 17:06:22.330 E/AndroidRuntime(22586): java.lang.ExceptionInInitializerError
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.baidu.mapsdkplatform.comapi.map.i.a(Unknown Source:0)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.baidu.mapapi.map.MapView.a(Unknown Source:2)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.baidu.mapapi.map.MapView.<init>(Unknown Source:17)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at cn.qiuxiang.react.baidumap.mapview.BaiduMapView.<init>(BaiduMapView.kt:24)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at cn.qiuxiang.react.baidumap.mapview.BaiduMapViewManager.createViewInstance(BaiduMapViewManager.kt:26)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at cn.qiuxiang.react.baidumap.mapview.BaiduMapViewManager.createViewInstance(BaiduMapViewManager.kt:20)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:47)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:256)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.view.Choreographer.doFrame(Choreographer.java:809)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.os.Handler.handleCallback(Handler.java:938)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.os.Looper.loop(Looper.java:236)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at android.app.ActivityThread.main(ActivityThread.java:7876)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at java.lang.reflect.Method.invoke(Native Method)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
12-16 17:06:22.330 E/AndroidRuntime(22586): Caused by: java.lang.IllegalStateException: you have not supplyed the global app context info from SDKInitializer.initialize(Context) function.
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.baidu.mapsdkplatform.comapi.a.e(Unknown Source:10)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.baidu.mapapi.BMapManager.getContext(Unknown Source:4)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	at com.baidu.mapsdkplatform.comapi.map.i.<clinit>(Unknown Source:0)
12-16 17:06:22.330 E/AndroidRuntime(22586): 	... 25 more
12-16 17:06:22.334 D/OOMEventManagerFK(22586): checkEventAndDumpForJE: 0

**Comment by gdmec07140512** [comment]
+1
