### ISSUE TITLE
无法定位，定位无效

### ISSUE THREAD

**Issue by qq895627041** [qiuxiang/react-native-baidumap-sdk#70]
一个栈，使用两次定位，第一次可以正常使用，第二次无法进行定位，且返回会导致app 闪退

**Comment by qiuxiang** [comment]
请提供重现的方法

**Comment by qq895627041** [comment]
`Process: com.zajymanager.app, PID: 5956
                                                                   java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
                                                                       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
                                                                       at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:32)
                                                                       at cn.qiuxiang.react.baidumap.modules.BaiduMapGeocodeModule$geoCoder$2$1.onGetReverseGeoCodeResult(BaiduMapGeocodeModule.kt:46)
                                                                       at com.baidu.platform.core.b.e.a(Unknown Source)
                                                                       at com.baidu.platform.base.c.run(Unknown Source)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:224)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5958)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)`

崩溃后得错误 信息

**Comment by qq895627041** [comment]
`    Location.init ();
    Location.addLocationListener (location => {
      Geocode.reverse ({
        latitude: location.latitude,
        longitude: location.longitude, 
      }).then (res => {
        this.setState ({
          address: res.district + res.description,
        });
      });
      this.setState ({location});
      this.location ();
    });
    Location.start ();`

**Comment by qq895627041** [comment]
`    Location.init ();
    Location.addLocationListener (location => {
      Geocode.reverse ({
        latitude: location.latitude,
        longitude: location.longitude, 
      }).then (res => {
        this.setState ({
          address: res.district + res.description,
        });
      });
      this.setState ({location});
      this.location ();
    });
    Location.start ();`
这是操作得方法

**Comment by qiuxiang** [comment]
你的代码能好好排一下？ https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by qiuxiang** [comment]
什么叫“两次使用定位”？

**Comment by qiuxiang** [comment]
还有你说的栈到底是什么？

**Comment by SXZXD** [comment]
第一个页面使用定位正常，然后跳转页面重新定位，定位失效，返回得时候，app闪退

**Comment by qiuxiang** [comment]
我知道问题是什么了，这里是因为我在实现 GeocodeModule 的时候用了 hack 的方法，导致 `search` 与 `reverse` 无法“并发”，也就是必须确保 `reverse` 完成之前，不能调用第二次 `reverse`。

你的问题在于，把 `reverse` 放在了两个同时运行的 `LocationListener` 里，这很可能会出现，2 个 `reverse` 同时调用，为了解决你的问题，必须保证只能有一个 `Location` 在运行。
